### ISSUE TITLE
ridesharing/ manage customer driver signup properly

### ISSUE THREAD

**Issue by sayeed1999** [sayeed1999/Ride-Sharing-Platform#20]
Possible criteria:
- [ ] when user is received in ridesharing, dont insert user in db if user has not role customer or driver
- [x] if a user with driver role signs up in auth service, insert driver entity in driver table of ridesharing db
- [x] if the user then adds customer role with update endpoint in auth service, insert customer entity in customer table of ridesharing db
- [ ] if user updates mobile number, but user is not present in ridesharing db, then insert
- [ ] if user updates mobile number, you may need to update both customer and driver table

**Comment by NafisianCastle** [comment]
@sayeed1999  I saw you added `username `property. Does it currently come from Auth?
